export const CONFIG_FIND_BY_ID_SQL = `
  SELECT
    CONFIG_ID,
    PROJECT_ID,
    CUSTOMER_NAME,
    TELEGRAM_BOT_NAME,
    TELEGRAM_BOT_LINK,
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_BOT_CHATID,
    WEBHOOK_URL,
    WEBHOOK_LOCAL_PORT,
    OPENAI_API_KEY,
    SHOPEE_CREDENTIAL,
    SHOPEE_SECRET_KEY,
    SHOPEE_AFFILIATE_ENDPOINT,
    SHOPEE_AFFILIATE_TIMEOUT,
    SHOPEE_AFFILIATE_SUBIDS,
    CREATEDAT,
    UPDATEDAT
  FROM TblConfig
  WHERE CONFIG_ID = ?
  LIMIT 1
`;
